### ISSUE TITLE
When selecting substance from sidebar, compound is loaded

### ISSUE THREAD

**Issue by cmgrulke** [Chemical-Curation/chemcurator_vuejs#118]
**As a** *user*
**I want** *to see the compound information associated with the substance if I select it from sidebar*
**So that** *I understand the substance better when browsing chemicals*

**Acceptance Criteria:**
When I select a DTXSID from the sidebar on the substance page, the compound editor and DTXCID and calculated properties are populated.

**Test(s):**

**Comment by michael-barbour** [comment]
Added a blocker for #101 due to the rework for compound loading that it adds.

**Comment by scaduto** [comment]
After countless testing I have come to the conclusion that the compound and computed properties are pulled in properly as a result of https://github.com/Chemical-Curation/chemcurator_vuejs/pull/109. I will be reverting all revisions I have made to this branch which allowed for the computed properties to show properly in my environment as I have realized that the limiting factor for having them shown was issues in my environment with the resolver. For the purpose of this ticket, I will be adding in e2e tests to verify those computed properties. **REVIEWER** please let me know if there are any issues testing this one and if there should be anything else added.

**Comment by scaduto** [comment]
![image](https://user-images.githubusercontent.com/62891235/101510061-6da62b80-3947-11eb-971f-51e07c305da1.png)

Previously, verification of the CID after selecting a substance from the tree was commented out, which included verifying the computed properties below as such:

![image](https://user-images.githubusercontent.com/62891235/101510210-a34b1480-3947-11eb-977d-9f3771567052.png)

Even without my changes, this functionality now works properly.

**Comment by scaduto** [comment]
After speaking with @michael-barbour this functionality was "accidentally" corrected by him in https://github.com/Chemical-Curation/chemcurator_vuejs/issues/101

![image](https://user-images.githubusercontent.com/62891235/101514862-bcee5b00-394b-11eb-975e-be7a80101fc7.png)
