### ISSUE TITLE
Defined Compound save bug (no dtxcid)

### ISSUE THREAD

**Issue by cmgrulke** [Chemical-Curation/chemcurator_vuejs#134]
**Describe the bug**
When saving a new compound, the dtxcid does not appear in the "record compound id" field and the properties are not provided

**To Reproduce**
1. Go to the substance page
2. Choose defined compound and draw a new structure not already stored by the api
3. Press save 
![image](https://user-images.githubusercontent.com/17733173/101665362-e4f8bf80-3a1a-11eb-8253-90077ecf49d9.png)
4. The "record compound id" and calculated fields remain empty and the "Save Compound" is not disabled, but the save was successful. If I delete a methyl group and add it back in, the content loads.
![image](https://user-images.githubusercontent.com/17733173/101665787-6d776000-3a1b-11eb-8399-8b1b05e70228.png)

**Expected behavior**
I expect after the save, for the compound id and calculated properties to appear in the form and for the 

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: chrome
 - observed on prod release at https://ccte-chemreg.epa.gov

**Additional context**
Relevant closes tickets: #55 and #32

**Comment by debboutr** [comment]
`indigo.IndigoException: element: bad valence on F having 2 drawn bonds, charge 0, and 0 radical electrons`

we aren't currently dealing w/ an error like this. the compound is being saved, but indigo is throwing this error when we fetch the made compound.

@cmgrulke I'm noticing that once I load the CID into the input if the user switches to IllDefined after making a defined compound, the CID will still be in the ID input box. I've taken the liberty to clear this, but if the user then again switches back to the Ketcher window the data up top will be gone but the compound will still be in the ketcher window. What should we do with the data in that window when the QST is switched to another window? should we just clear out ketcher when the use switches to the marvin window and vice versa?

**Comment by debboutr** [comment]
the indigo error above is particularly pernicious because the compound gets saved but the error is thrown on the get when the molecularWeight is being calculated.
