### ISSUE TITLE
Substance save bug (dtxcid relationship not saving)

### ISSUE THREAD

**Issue by cmgrulke** [Chemical-Curation/chemcurator_vuejs#135]
**Describe the bug**

**To Reproduce**
1. Start this a substance record
![image](https://user-images.githubusercontent.com/17733173/101667540-723d1380-3a1d-11eb-9bd6-cbb756ec4915.png)

2. Alter the structure to a different compound (note it cannot be a compound that is linked to a different substance or the submit would fail)
![image](https://user-images.githubusercontent.com/17733173/101667746-b3352800-3a1d-11eb-97c3-2505332074e7.png)

3. See Save Substance is disabled (bug 1)
4. Alter another substance field like the name
5. Save the substance
6. See the structure associated with the substance reverts
![image](https://user-images.githubusercontent.com/17733173/101668301-5d14b480-3a1e-11eb-9a0d-4e43e1d8411a.png)

**Expected behavior**
As a record compound id changes on the substance, this change should enable "Save Substance" (as long as the DTXCID in the record compound id is different than currently stored for that substance by the API).  When I press save, the associatedCompound should be updated if it has been changed.

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**
The associated ticket #97 did not clarify that the record compound id should be considered the id associatedCompound.  Bad product owner for not making this clear, but this linkage must be updated as part of the save action.

**Comment by jtumkur** [comment]
- Pull up a chemical. It finds a different CID.
- Click on Substance to save. 
- If no CID is associated. Then structure should not be saved.
- Relationship between sub and compound is clean or dirty.
- Ability to save is needed. What is the easy implementation way should be thought?
 - What data is unclean about the substance. CID is treated as an attribute for the substance.

**Comment by jtumkur** [comment]
As the compound is changed and queried a different DTXid is retrieved.
Click on Save compound only patch of the mole file is done for the CID

**Comment by jtumkur** [comment]
- Variations can happen based on the Structure type.
- Is a new data model needed to track this?

**Comment by jtumkur** [comment]
- Have 2 Save button for Substance and Compound.
- As per the payload save include the CID

**Comment by debboutr** [comment]
@cmgrulke just to be sure, if you are at a substance page that initially has an associated compound and then were to move the query structure type to none and click Save Substance, you would want that to remove the association, right? so if you were to refresh the page after the compound would be gone?

**Comment by jtumkur** [comment]
#97 was the ticket that caused this.

**Comment by jtumkur** [comment]
Add as a related ticket  - Additional filter if there is no DTXSid
