### ISSUE TITLE
When selecting substance from sidebar, compound is nulled if appropriate

### ISSUE THREAD

**Issue by cmgrulke** [Chemical-Curation/chemcurator_vuejs#138]
**As a** *user*
**I want** *the compound to be nulled out if a substance is read into the substance page that has no compound*
**So that** *I understand the substance better when browsing chemicals*

**Acceptance Criteria:**
When I select a DTXSID from the sidebar on the substance page or arrive on one from a search, the compound displayed always represents the substance that is loaded (including no structure if there is no structure

**Test(s):**

**Comment by stevenhausman-gdit** [comment]
@cmgrulke I feel like this is the current behavior when using the sidebar tree. Especially now with the "Toggle Sidebar" button not being visible when a Substance is loaded (#119).

_Steps to reproduce_
- Create & save a new substance without defining a "Structure Type"
![138-create-fake-substance](https://user-images.githubusercontent.com/74921039/102385418-d458c400-3f9b-11eb-8b8f-f9b35732c5c6.png)
- If we open this same new Substance from the "Toggle Sidebar" tree I do not have a compound appear on the page

**note** Although I did notice that if I open a Substance that has an associated Compound, then change the "Structure Type" to "None" I cannot save that removal of association between that Compound and Substance. The "Save Substance" button is greyed out and the 'Save Compound" button is also gone (when selecting "None").

_Steps to recreate similar behavior_
I was able to get a 'dangling Compound' (like you are describing) while using the Search Bar.
- Load 'Substance A' (that has a compound association) via either Search or Tree 
![138-load-substance-w-compound](https://user-images.githubusercontent.com/74921039/102387241-226ec700-3f9e-11eb-8215-8f4fd13f864f.png)
- Search for a 'Substance B' that does not have a compound
- Now I see 'Substance B' 's details and the Compound associated with 'Substance A'
![138-load-substance-wo-compound-dangling](https://user-images.githubusercontent.com/74921039/102387259-27cc1180-3f9e-11eb-93fa-95f1d7832d20.png)

**? Would submitting/modifying tickets along these lines be more appropriate ?**
- Clearing Substance Form on navigation (Compound is cleared on navigation)
- Clearing Substance Form/Compound before returning SF/C from Search (essentially this ticket)
- Clearing contents of Search Box after executing search _bonus ticket_
- Saving the removal of a Compound's association with a Substance ("Structure Type" set from a_type to "None") _bonus ticket_

**Comment by cmgrulke** [comment]
So anytime a substance is loaded into the substance page, I want the compound that is associated with the substance loaded in as well.  I think of this as rather than a clear on navigating away, it needs to be an active load on navigation to the page (and I consider the clicking of a new substance in the sidebar or the search of a substance to be a navigation to a substance page).

**Comment by jtumkur** [comment]
Single search page has search link

Browse page has a
