### ISSUE TITLE
Dockerize Front End

### ISSUE THREAD

**Issue by dmlyons2** [Chemical-Curation/chemcurator_vuejs#17]
**As a** dev ops engineer
**I want** the application to be served from a docker container
**So that** so that I can easily monitor and deploy it in production

**Acceptance Criteria:**
A dockerfile in the repo that will allow me to create and deploy the application in Production
A wiki page in this repo that explains the details on how to get it up and running.

**Test(s):**

**Comment by mcovalt** [comment]
What Docker version are we targeting?

**Comment by dmlyons2** [comment]
RHEL `1.13.1 Build 4ef4b30/1/13/1`
