### ISSUE TITLE
New Dev Setup Documentation

### ISSUE THREAD

**Issue by dmlyons2** [Chemical-Curation/chemcurator_vuejs#18]
**As a** new developer
**I want** to be able to get the dev environment up and running quickly
**So that** I can quickly start contributing to the team

**Acceptance Criteria:**
A wiki page with instructions on how to get started with the app

**Comment by dmlyons2** [comment]
Note that there is not a PR for this, it is just changes to the wiki.

**Comment by mcovalt** [comment]
Looks good. I added the command to install `@vue/cli` globally which is required.
