### ISSUE TITLE
Application Security Setup

### ISSUE THREAD

**Issue by dmlyons2** [Chemical-Curation/chemcurator_vuejs#24]
**As a** product owner
**I want** some security on my webapp
**So that** only authorized folks can get to edit pages and make changes

**Acceptance Criteria:**

- Create a way to login to the application
- I will create users in the admin application that can login to this UI and I will create a role in the admin application called ui-curator. 
- The only page you can get to when not logged in is the login page. Both Welcome and About pages should be for logged in users only.
- If the user is not logged in they are redirected to the login page then redirected back to the welcome page 
- Only people that I give the role of ui-curator can get into the application.

**Test(s):**
User must be in group ui-curator to log into front end

**Comment by mcovalt** [comment]
Once https://github.com/Chemical-Curation/chemcurator_django/pull/63 is merged in:

You can

- `POST` on `/login/` with [HTTP Basic Authentication](https://en.wikipedia.org/wiki/Basic_access_authentication) to log the user in. This will create a session and send back a cookie with the session ID. The logged in user information will be sent back in the response body as a JSON. Subsequent requests will be authenticated automatically using this session cookie.
- `GET` on `/login/` to get the currently signed in user.
- `DELETE` on `/login/` will delete the session data and log the user out.

Here is an example of the initial `POST` to `/login/` using axios with HTTP Basic Authentication:
```javascript
var API_URL = process.env.API_URL;
axios.post(API_URL + "/login/", {}, {
  auth: {
    username: uname,
    password: pass
  }
});
```

**Important security notice:**
To prevent CSRF, we are using a relatively new cookie attribute "SameSite: Strict". See compatible browsers [here](https://caniuse.com/#feat=same-site-cookie-attribute). Allowing the user to login with a browser that does not support this feature is not a great idea. We can determine the browser support on the login page by examing the browser's `User-Agent`.
