### ISSUE TITLE
favicon

### ISSUE THREAD

**Issue by cmgrulke** [Chemical-Curation/chemcurator_vuejs#27]
**As a** *user*
**I want** *an icon on the header of the application and in the tab in my browser*
**So that** *I can easily tell this website from any other*

**Acceptance Criteria:**
Place the attached icon or a similar icon that gives the user a chemistry feel on the left of the header and make it the favicon for the app.

**Test(s):**

**Comment by cmgrulke** [comment]
![favicon](https://user-images.githubusercontent.com/17733173/75584802-9dcab080-5a3e-11ea-86ab-9a1c770bebe9.png)

This is what I was using, but any chemistry associated thing would be great other than a flask (that is used by our sample inventory application).

**Comment by mwfrost** [comment]
![Screen Shot 2020-04-08 at 7.26.54 AM.png](https://images.zenhubusercontent.com/5be34a63f724c70c7221c972/db5d2b9b-3757-42b8-a593-3aebacbaa57c)

@cmgrulke How about this little carbon ring with green highlights?

**Comment by cmgrulke** [comment]
You mean the little benzene ring?  Works for me
