### ISSUE TITLE
Search box for inchikey or dtxcid

### ISSUE THREAD

**Issue by cmgrulke** [Chemical-Curation/chemcurator_vuejs#29]
**As a** User
**I want** to be able to search for a compound based on compound id or inchikey
**So that** I can see the compound in the appropriate structure editor

**Acceptance Criteria**
When logged in, there is a search box in the header bar.  Typing an inchikey or compound_id into that search bar and hitting enter will take me to the home page.  The compound_id will be displayed and the structure will appear in the appropriate editor (MarvinJS or Ketcher).  If no compound exists for the query a message will inform me of that.

If it is a duplicate, do not display in ketcher and notify user that it is a dup.

**Comment by debboutr** [comment]
if the compound is found and loaded into the MarvinJS window would you also like to have the text that was imported in the text area that we have below that window for viewing or just leave that blank with only the compound in the Marvin window?

**Comment by cmgrulke** [comment]
I think putting it in the text area would be great.

**Comment by debboutr** [comment]
for loading data into ketcher I've found this in the source files that may be a good target for us to interact with the window, not sure what we will have to do to grab the `ketcher` object in this line, but it's a start anyway
[setMolecule](https://github.com/epam/ketcher/blob/c9ee5d3b874e29961ab8d57c96dc3c7ad47942e3/src/template/demo.html#L78)

I've tried to grab the `ketcher` object in the manner seen [here](https://github.com/epam/ketcher/issues/3), but get the error:

`vue.runtime.esm.js?2b0e:1888 DOMException: Blocked a frame with origin "http://localhost:8080" from accessing a cross-origin frame.`
