### ISSUE TITLE
Display structure derived information based on structure in ketcher.

### ISSUE THREAD

**Issue by cmgrulke** [Chemical-Curation/chemcurator_vuejs#32]
**As a** User
**I want** to be able to see the molecular weight, molecular formula, smiles, and inchikey for the structure in the ketcher window
**So that** the interface facilitates checks on whether my structure matches with the concept I am trying to structurally capture

**Acceptance Criteria**
- A panel exists between the CID/structure_type pulldown menu and the ketcher drawing iframe with a label of "Structure Derived Information" when the Structure Type is defined compound.  
- the calculated molecular weight, molecular formula, smiles, and inchikey for the structure (as returned in a defined compound's detail view in the api) are displayed in the panel
- The fields are updated as the structure in the ketcher iframe is changed, just like the CID.
- If the compound is not known to the api, the information in the panel (like the CID) should be left empty

**Comment by cmgrulke** [comment]
I would like to remove the "Molfile text box can be deleted and there no longer needs to be an import/export button." acceptance criteria, since the acceptance criteria in issue#19 were not clear enough and this textbox is not on the page.  Since this issue is already pointed, I would like our Sprint Master to concur and make the change.

**Comment by debboutr** [comment]
[Audio from ticketting...](https://drive.google.com/file/d/1qCXK4r350TxnV6k7T3rErq--FBiBwJsP/view?usp=sharing)

**Comment by debboutr** [comment]
@cmgrulke in review of this ticket, we may have mis-understood this bullet point 

> The fields are updated as the structure in the ketcher iframe is changed, just like the CID.

We have a working branch with the data displayed above the ketcher window from the DB's detail view, but it is not currently updating while editing. So, just to be clear, if there is an CID recognized, we need to keep up-to-date the info in this window? This will require an endpoint to return the updated indigo information which we don't currently have

One thing that we need to think about is when/how does a user get off working on a particular compound. If I'm drawing and a CID comes up, but I didn't want to do anything with that particular CID, what does the user do? There is no way to remove the found CID w/o a refresh, so I would think that there will need to be the ability to remove a compound from state that is not the intended compound that the user wants to work on?

**Comment by cmgrulke** [comment]
Let me try to clarify...  So when I edit the structure in the ketcher window, the CID will change in accordance with the search initiated by the new structure.  If there is no CID matching the new structure, the CID field should be empty.  Likewise, the fields listed here (molecular weight, molecular formula, smiles, and inchikey) would be empty if the CID field is empty.  If a CID was found, the molecular weight, molecular formula, smiles, and inchikey would be the ones for that CID.

You bring up a good point that there should be a revert capability, but I consider that a substance level request (that would for a substance revert the user back to having the CID that was originally associated with that substance).  When an edit is made to the structure in the ketcher window, you are only working on the same compound if that compound is the one returned from the search.  This is part of the complexity of dealing with two objects of equal primacy in a single form.  For my users, they will look at the substance as having greater primacy than the structure (even though both are in fact stand-alone, full objects in their own right that happen to have a 0/1:0/1 relationship), so the UI needs to keep things centered on the substance (since it is the substance page) and as the structure changes, you are altering the compound that will be be linked to the substance if the substance changes are submitted.

If we need a meeting to clarify this complexity, I will find some time on our calendars.  I think me narrating my use of the interface while you watch would help a lot.

**Comment by cmgrulke** [comment]
Also note that my above comment ("When an edit is made to the structure in the ketcher window, you are only working on the same compound if that compound is the one returned from the search.") is only true for defined compounds, not ill defined compounds which have a different business process.
