### ISSUE TITLE
Query Structure type table 

### ISSUE THREAD

**Issue by cmgrulke** [Chemical-Curation/chemcurator_vuejs#39]
**As a** *admin*
**I want** *to see a table containing the query structure types that are in the database on the controlled vocabulary page
**So that** *I can understand the query structure types that are currently in use

**Acceptance Criteria:**
On the Controlled Vocabulary page (issue #38), add a table for query structure types.  The table should have the following columns: name, label, short_description

**Test(s):**

**Comment by michael-barbour** [comment]
As Query Structure Type is a controlled vocabulary I built it as its own table on this page.  It doesn't currently show the name (the name column actually shows the label, as I had assumed the database name was not meant for users), so modifications may be needed.

![image](https://user-images.githubusercontent.com/22226925/90262317-2803a700-de1c-11ea-8e1f-53186f549449.png)

**Comment by debboutr** [comment]
@cmgrulke , we pretty much already have this table implemented, just need to have columns for both name and label. Does that seem okay to you? This will add these columns for all ControlledVocabulary tables on this page.
![image](https://user-images.githubusercontent.com/7052993/91476341-b717b280-e851-11ea-9d60-53a973d87582.png)

**Comment by cmgrulke** [comment]
Sorry for not replying earlier.  This is fine with me since it meets my acceptance criteria.
