### ISSUE TITLE
List Detail Page

### ISSUE THREAD

**Issue by cmgrulke** [Chemical-Curation/chemcurator_vuejs#52]
**As a** *anonymous user*
**I want** *to be able to view the details for a list*
**So that** *I can see all the metadata regarding the list from the UI*

**Acceptance Criteria:**
* clicking on the list name in the table on the List Page (issue #51) brings up a new view with list details
* all list attributes are displayed in the detail page

**Comment by debboutr** [comment]
[Audio from ticketting...](https://drive.google.com/file/d/1PVQTdhuFu234tadxFmiA8xol5vwjMcVB/view?usp=sharing)
