### ISSUE TITLE
Home page

### ISSUE THREAD

**Issue by cmgrulke** [Chemical-Curation/chemcurator_vuejs#53]
**As a** *anyonymous user*
**I want** *to land on an informative about page for ChemReg with general statistics*
**So that** *I can get an understanding of the size of the underlying data and the purpose of the data system*

**Acceptance Criteria:**
* when coming to the ChemReg UI, the user lands on the about page (even when not logged in)
* the landing page displays the number of Lists, Substances, and Compounds currently stored in ChemReg 
* the landing page contains a text box explaining the purpose of ChemReg (left as "Lorem ipsum...." for now)
* there is a login panel on the about page if the user is not logged in

**Comment by cmgrulke** [comment]
For inspiration, I give you the about page for chemtrack.  This not what it needs to look like, but provides a feel for a landing page that I approved of in the past.
![image](https://user-images.githubusercontent.com/17733173/88820943-fccc5700-d18f-11ea-8f47-380685398474.png)

**Comment by mwfrost** [comment]
@cmgrulke Chris, should the path to this page be `/about`? 

If so, then when a non-authenticated user goes to the root URL at `/`, they should be bounced to `/about`, but if an authenticated user visits `/`, they should stay there with the ketcher/marvin UI?
