### ISSUE TITLE
Substance Page

### ISSUE THREAD

**Issue by cmgrulke** [Chemical-Curation/chemcurator_vuejs#54]
**As a** *anonymous user*
**I want** *to be able to see chemicals*
**So that** *I can know what a substance means chemically*

The structural editor page that is landed on after login or a search needs to be extended to become the substance page.  It should continue to be accessible via search (since landing on it will not longer be the case upon login after issue #53 is completed) 

**Acceptance Criteria:**
* The structure editor should shift to the right side of the page. 
* on the left, there should be fields to input substance related data
* all fields that can be input for a substance and a compound should be available on the page
* search results should display not just the structural information, but also the information from the linked substance.
* for anonymous users, editing fields in the form should be disabled (a separate ticket will focus on the editing fields and pull downs).

**Comment by cmgrulke** [comment]
![image](https://user-images.githubusercontent.com/17733173/88819795-75321880-d18e-11ea-9875-3901ab232f5c.png)
This is a possible layout for the page, but please feel free to improvise... the submit buttons and functionality are not part of this ticket.

**Comment by dmlyons2** [comment]
This is a 4 / 8 column layout

**Comment by michael-barbour** [comment]
Substance.associated_compound [chemcurator_django 90](https://github.com/Chemical-Curation/chemcurator_django/issues/90) was created as a many to one relationship from compound to substance.  This will need to be change to a one to one to ensure the jsonapi fetch is coming back correctly.
