### ISSUE TITLE
Substance Page tree browsing

### ISSUE THREAD

**Issue by cmgrulke** [Chemical-Curation/chemcurator_vuejs#56]
**As a** *anonymous user*
**I want** *to be able to navigate and browse chemicals*
**So that** *i can look through the chemicals stored by ChemReg*

**Acceptance Criteria:**
- A link in the navbar that enables the user to see the substance page (with no chemical)
- when going to the substance page via the navbar, a collapsible panel is available on the left of the page that contains a tree
- the tree contains a heirarchy with first the last updated at date, then the curator, then the substances (denoted using DTXSID)
- when clicking on a DTXSID, the substance is displayed in the substance form.

**Test(s):**

**Comment by cmgrulke** [comment]
Here is a snip of the current tree in old ChemReg
![image](https://user-images.githubusercontent.com/17733173/89223200-64c1d980-d5a4-11ea-90b6-629a918931dd.png)

**Comment by michael-barbour** [comment]
`{{baseUrl}}/substances?sort=sid,displayName`

**Comment by debboutr** [comment]
[Audio from ticketting...](https://drive.google.com/file/d/1n0pRbl8rA6hqVkotEVCReFm8JGkKvOfq/view?usp=sharing)
