### ISSUE TITLE
Ill-defined compound editing on substance page

### ISSUE THREAD

**Issue by cmgrulke** [Chemical-Curation/chemcurator_vuejs#58]
**As a** *curator*
**I want** *to be able edit and submit structures on the substance page*
**So that** *the new structures get stored in the database and compound ids*

**Acceptance Criteria:**
- if an ill-defined compound displayed in marvinjs is in any way different than that loaded for the substance, a "Save Structure" button is available
- when save structure button is pressed, if the substance had been loaded with an ill-defined compound, the structure is PATCHED to the api using the CID from which it was originally loaded
-- if the save is successful, the compound id is displayed in the form.
-- if the save is not successful, the user is notified of the error
- when the save structure button is pressed and the substance had been loaded without an ill-defined compound, the structure is POSTED to the api
-- if the save is successful, the compound id is displayed in the form.
-- if the save is not successful, the user is notified of the error

**Comment by debboutr** [comment]
[Audio from ticketting...](https://drive.google.com/file/d/1jHVxCVmKAz-Vq1ICsot6XcblV1HcIo_P/view?usp=sharing)
