### ISSUE TITLE
Compound "new data" navigation block

### ISSUE THREAD

**Issue by cmgrulke** [Chemical-Curation/chemcurator_vuejs#59]
**As a** *curator*
**I want** *to be blocked from leaving a page without saving changes to the compound*
**So that** *I don't lose edits to the compound*

**Acceptance Criteria:**
Edits to a compound are apparent to the user if the "Save Structure" button is available to be pressed
If the save structure button is not disabled, the user when attempting to navigate away from the page should be prompted that unsaved changes exist for a compound and asked to confirm that they are ok losing those changes.

**Comment by mwfrost** [comment]
https://forum.vuejs.org/t/detect-browser-close/5001

**Comment by debboutr** [comment]
[Audio from ticketting...](https://drive.google.com/file/d/12QaPtk7cYQSTzFrqq8992rcmFJ-kkACA/view?usp=sharing)

**Comment by mwfrost** [comment]
Defined compound to demo with: 
AGAHNABIDCTLHW-UHFFFAOYSA-N
