### ISSUE TITLE
Substance Page Structure Types

### ISSUE THREAD

**Issue by cmgrulke** [Chemical-Curation/chemcurator_vuejs#60]
**As a** *curator*
**I want** *the Structure Type pulldown menu to have "None", "Defined Compound", and all the Query Structure types to select from*
**So that** *I can pick the right structure type for my substance*

**Acceptance Criteria:**
- the structure type pull down menu allows select of "None", "Defined Compound", and all the Query Structure types from the API
- when "None" is selected, the CID field should be empty and no structure sketcher should be displayed
- when "Defined Compound is selected, the Ketcher structure sketcher is displayed
- when any of the query structure types is selected, the MarvinJS structure sketcher is displayed

**Comment by debboutr** [comment]
[Audio from ticketting...](https://drive.google.com/file/d/1xk6xW7C_GfsqVC5hR5x1i5yAl78iWBKk/view?usp=sharing)
