### ISSUE TITLE
Substance Page synonyms

### ISSUE THREAD

**Issue by cmgrulke** [Chemical-Curation/chemcurator_vuejs#61]
**As a** *anonymous user*
**I want** *to be able to see a table of synonyms on the substance page*
**So that** *I know the names that are associated with this substance*

**Acceptance Criteria:**
- At the bottom of the substance page, a table of synonyms is displayed
- the table shows the identifier, source, synonym_type, synonym_class and the qc_note
- as an anonymous user, I should not be able to change any of them

**Comment by debboutr** [comment]
[Audio from ticketting...](https://drive.google.com/file/d/1YVaJo8NnEARwbkAzawbWcrS_RhsQa812/view?usp=sharing)

**Comment by debboutr** [comment]
this closes with issue #62 and PR #81
