### ISSUE TITLE
Substance page synonym editting

### ISSUE THREAD

**Issue by cmgrulke** [Chemical-Curation/chemcurator_vuejs#62]
**As a** *curator*
**I want** *to be able to edit the synonyms in the synonym table on the substance page*
**So that** *I can correct names and other identifiers associated with a substance*

**Acceptance Criteria:**
- the table allows edit in place with pull down menus for the controlled vocabulary fields?

**Test(s):**

**Comment by debboutr** [comment]
[Audio from ticketting...](https://drive.google.com/file/d/1BjduyswlTt37TspV-0ucO3HCS-En5zy_/view?usp=sharing)
