### ISSUE TITLE
Substance page list table

### ISSUE THREAD

**Issue by cmgrulke** [Chemical-Curation/chemcurator_vuejs#66]
**As a** *anonymous user*
**I want** *to be able to see a table of lists on the substance page*
**So that** *I know which lists (records) are associated with this substance*

**Acceptance Criteria:**
- Below the substance relationships table, lists table is displayed
- the table shows the List.label, record.rid, record.external_id, record.identifiers (newline separated list of all record identifiers) for which the substance displayed is a record's mapped substance
- I should not be able to change anything in the table

**Comment by debboutr** [comment]
[Audio from ticketting...](https://drive.google.com/file/d/1wYBg1Wf86_VVMcOWLTRD2A6Ya-X_TvyW/view?usp=sharing)

**Comment by michael-barbour** [comment]
> record.rid, record.external_id, record.identifiers (newline separated list of all record identifiers) 

With this being a many to many field this has a high risk of being a slow or oversized query, both on the request side and on the render side.  It might be better to either:

1. Split this into two tables. Where there is only one list table and clicking on a row opens/populates the records as a table.
2. Make this a records table with a column references List.label.  Then we can take advantage of the smaller side of the 1 to many relationship.

**Comment by michael-barbour** [comment]
> > record.rid, record.external_id, record.identifiers (newline separated list of all record identifiers) 
> 
> With this being a many to many field this has a high risk of being a slow or oversized query, both on the request side and on the render side.  It might be better to either:
> 
> 1. Split this into two tables. Where there is only one list table and clicking on a row opens/populates the records as a table.
> 2. Make this a records table with a column references List.label.  Then we can take advantage of the smaller side of the 1 to many relationship.
> 
> I'm unsure what the expected upper bound is for records to a list, but if it exceeds 50 or so, I think the experience of using this table will be quite frustrating.
> 
> Edit:  Upon further inspection it seems this problem repeats itself going from record to record identifiers.

After talking with @cmgrulke, it seems like strategy number 2 fits better.  This really will be a "records table" with a reference to the list label.
