### ISSUE TITLE
Structure search on change in ketcher

### ISSUE THREAD

**Issue by cmgrulke** [Chemical-Curation/chemcurator_vuejs#67]
**As a** curator
**I want** the defined compound structure i am editting to be searched on change
**So that** I know if it exists in the database

**Acceptance Criteria**
when a structure in ketcher changes, it is searched against the defined compound api
if it exists, its dtxcid is displayed.

**Comment by debboutr** [comment]
[Audio from ticketting...](https://drive.google.com/file/d/1ChLaDZtCM-IOfrJHIzEAu_SkIW7F2gRr/view?usp=sharing)
