### ISSUE TITLE
redirect user to unauthorized page if they attempt to access restricted material

### ISSUE THREAD

**Issue by cmgrulke** [Chemical-Curation/chemcurator_vuejs#69]
**As a** authenticated user
**I want** to be forwarded to an "unauthorized page" when attempting to access a restricted page
**So that** I know that where I tried to go is not accessible

**Acceptance Criteria**
If a user doesn't have the privileges to see a page the attempt to navigate to, send them to an unauthorized page that tells them to contact the site administrator to gain access.  
(An example would be if a non-admin user attempted to navigate to the controlled vocabulary page #38 ).

**Comment by kdionisio** [comment]
@dmlyons2  Do we have a email or contact plan for our users????

**Comment by debboutr** [comment]
[Audio from ticketting...](https://drive.google.com/file/d/1rpdvGFCRJ8KCeamByWTgnwGIDk5aewvX/view?usp=sharing)
