### ISSUE TITLE
Use of Ketcher to get v3000 molfiles

### ISSUE THREAD

**Issue by cmgrulke** [Chemical-Curation/chemcurator_vuejs#73]
**As a** cheminformatician
**I want to** use v3000 export from ketcher not v2000
**So that** I can use the latest rather than an old chemical storage format

Ketcher (as managed by ePAM) olny exports v2000 format molfiles.  This pull request (https://github.com/Chemical-Curation/ketcher/pull/3) makes it so that our version of Ketcher will export v3000 molfiles (if a v3000=true flag is sent to the getMolFile() as is done on the button in demo.html).  Please use this capability to get the v3000 molfile for chemicals in the Ketcher editor

**Acceptance Criteria:**
- use v3000 molfiles from Ketcher
- only includes changing parameter flag for get mol file request

**Comment by debboutr** [comment]
[Audio from ticketting...](https://drive.google.com/file/d/1v_mmZoO2GO1rd4VFAvy9566z8XluETQ4/view?usp=sharing)

**Comment by mwfrost** [comment]
example inchikey for demo: AGAHNABIDCTLHW-UHFFFAOYSA-N
