### ISSUE TITLE
Search bar uses resolver api

### ISSUE THREAD

**Issue by cmgrulke** [Chemical-Curation/chemcurator_vuejs#85]
**As a** *anonymous user*
**I want** *to search using the more robust functionality in the resolver api*
**So that** *i can view the substances I want more easily*

**Acceptance Criteria:**
The search in the nav bar no longer searches directly for DTXCID and inchikey, but instead searches using the resolver microservice ticketed in the blocking issue.

**Comment by jtumkur** [comment]
Using JSON API every request to the related object is saved.

Its better to have one JSON call.

**Comment by jtumkur** [comment]
As long as 2 APIS are deployed to docker, the bandwidth should be able to use it.
