### ISSUE TITLE
Remember me

### ISSUE THREAD

**Issue by cmgrulke** [Chemical-Curation/chemcurator_vuejs#90]
**As a** *user*
**I want** *the option to select "remember me" when I login*
**So that** *I don't have to login repeatedly*

**Acceptance Criteria:**
There is a remember me option in the login panel
When I select "remember me", I should be remembered for an easily configurable number of hours/days (set up by environment variable or the devops guy)
If I logout, the website will not remember me anymore so I will have to login the next time I want to use the application.

**Test(s):**

**Comment by jtumkur** [comment]
- Remember me should not be an option. 
- Autolog out should be extended period so that application can be used continuously. - 
    Timing for this extension TBD

**Comment by dmlyons2** [comment]
This was completed with the SESSION_COOKIE_AGE env var.
