### ISSUE TITLE
Markush menus on MarvinJS

### ISSUE THREAD

**Issue by cmgrulke** [Chemical-Curation/chemcurator_vuejs#95]
**As a** *curator*
**I want** *to be able to use additional menus that built into marvinjs but not currently displayed for repeating groups, smart R, R-group attachement, and radicals*
**So that** *I can more easily draw markush structures*

![image](https://user-images.githubusercontent.com/17733173/95212303-8bc2a480-07bb-11eb-88d6-b6b3dd564ccd.png)

**Acceptance Criteria:**
The additional menus shown in the image are available in the marvinjs editor

**Comment by cmgrulke** [comment]
I have these menus on in old ChemReg and it may be that all is that is needed is adding explicit data-toolbars options into the editor.html that is being using.  This is the line that I changed in my editor.html.

`<div id="sketch" data-toolbars="reporting"></div>`

**Comment by michael-barbour** [comment]
https://marvinjs-demo.chemaxon.com/latest/

**Comment by michael-barbour** [comment]
It looks like we are using a more recent version of marvin.  As such some of these tools seem to have changed their names/icons a little.  I believe [S-Group](https://docs.chemaxon.com/display/docs/tools-toolbar-left-toolbar.md#s-group) is simply a rename of what you're calling "repeating groups", but I'd like your confirmation as I'm unfamiliar with this tool.

> S-group
> Opens the S-group dialog to establish repeating units, SRU polymers, link nodes, or copolymers.

If you want to see with an example of the changes I'm expecting to make, this is a snapshot using the "reporting" tools (left side) toolbar on the latest version of marvin:  https://marvinjs-demo.chemaxon.com/latest/.  All the other tools seem the same.
