### ISSUE TITLE
Delete synonyms

### ISSUE THREAD

**Issue by cmgrulke** [Chemical-Curation/chemcurator_vuejs#98]
**As a** *curator*
**I want** *to be able to delete synonyms*
**So that** *I can ensure we don't have incorrect synonyms attached to a substance*

The synonym table has to provide a way to delete rows in the table.

**Acceptance Criteria:**
* There is an interface element in the synonym table that lets me delete rows.
* when rows are deleted, they issue a DELETE request to the api
* if there is an error, a message is provided to the user

**Comment by jtumkur** [comment]
Success and delete message tickets to be added by Chris
